packages:
  - "packages/*"
  - "examples/*"
  - "tools/*"
allowBuilds:
  "@playwright/browser-chromium": false
  "@swc/core": true
  "@vscode/vsce-sign": true
  core-js: true
  esbuild: true
  keytar: true
