packages:
  - "packages/*"
  - "examples/*"
  - "tools/*"
allowBuilds:
  "@playwright/browser-chromium": false
  "@swc/core": true
  "@vscode/vsce-sign": true
  core-js: true
  esbuild: true
  keytar: true
minimumReleaseAgeExclude:
  - '@rolldown/binding-android-arm64@1.2.1'
  - '@rolldown/binding-darwin-arm64@1.2.1'
  - '@rolldown/binding-darwin-x64@1.2.1'
  - '@rolldown/binding-freebsd-x64@1.2.1'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.1'
  - '@rolldown/binding-linux-arm64-gnu@1.2.1'
  - '@rolldown/binding-linux-arm64-musl@1.2.1'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.1'
  - '@rolldown/binding-linux-s390x-gnu@1.2.1'
  - '@rolldown/binding-linux-x64-gnu@1.2.1'
  - '@rolldown/binding-linux-x64-musl@1.2.1'
  - '@rolldown/binding-openharmony-arm64@1.2.1'
  - '@rolldown/binding-wasm32-wasi@1.2.1'
  - '@rolldown/binding-win32-arm64-msvc@1.2.1'
  - '@rolldown/binding-win32-x64-msvc@1.2.1'
  - rolldown@1.2.1
  - '@vitejs/plugin-react@6.0.5'
  - '@types/react@19.2.18'
