import { createContext, resolveConfig } from "../src"
import { preflight } from "../src/preflight"

test("preflight", async () => {
	expect(
		createContext(
			resolveConfig({
				corePlugins: {
					preflight: false,
				},
			}),
		).globalStyles,
	).toEqual({
		"*, ::before, ::after": {
			"--tw-backdrop-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-opacity": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-border-spacing-x": "0",
			"--tw-border-spacing-y": "0",
			"--tw-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-drop-shadow": "var(--tw-empty,/**/ /**/)",
			"--tw-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-figure": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-fraction": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-spacing": "var(--tw-empty,/**/ /**/)",
			"--tw-ordinal": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-x": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-y": "var(--tw-empty,/**/ /**/)",
			"--tw-pinch-zoom": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-color": "rgb(59 130 246 / 0.5)",
			"--tw-ring-inset": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-offset-color": "#fff",
			"--tw-ring-offset-shadow": "0 0 #0000",
			"--tw-ring-offset-width": "0px",
			"--tw-ring-shadow": "0 0 #0000",
			"--tw-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-scroll-snap-strictness": "proximity",
			"--tw-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-slashed-zero": "var(--tw-empty,/**/ /**/)",
			"--tw-transfrom-translate-default": "translate(var(--tw-translate-x, 0), var(--tw-translate-y, 0))",
		},
		"::backdrop": {
			"--tw-backdrop-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-opacity": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-border-spacing-x": "0",
			"--tw-border-spacing-y": "0",
			"--tw-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-drop-shadow": "var(--tw-empty,/**/ /**/)",
			"--tw-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-figure": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-fraction": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-spacing": "var(--tw-empty,/**/ /**/)",
			"--tw-ordinal": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-x": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-y": "var(--tw-empty,/**/ /**/)",
			"--tw-pinch-zoom": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-color": "rgb(59 130 246 / 0.5)",
			"--tw-ring-inset": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-offset-color": "#fff",
			"--tw-ring-offset-shadow": "0 0 #0000",
			"--tw-ring-offset-width": "0px",
			"--tw-ring-shadow": "0 0 #0000",
			"--tw-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-scroll-snap-strictness": "proximity",
			"--tw-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-slashed-zero": "var(--tw-empty,/**/ /**/)",
			"--tw-transfrom-translate-default": "translate(var(--tw-translate-x, 0), var(--tw-translate-y, 0))",
		},
	})
	expect(createContext(resolveConfig({})).globalStyles).toEqual({
		...preflight,
		"*, ::before, ::after": {
			"--tw-backdrop-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-opacity": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-border-spacing-x": "0",
			"--tw-border-spacing-y": "0",
			"--tw-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-drop-shadow": "var(--tw-empty,/**/ /**/)",
			"--tw-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-figure": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-fraction": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-spacing": "var(--tw-empty,/**/ /**/)",
			"--tw-ordinal": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-x": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-y": "var(--tw-empty,/**/ /**/)",
			"--tw-pinch-zoom": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-color": "rgb(59 130 246 / 0.5)",
			"--tw-ring-inset": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-offset-color": "#fff",
			"--tw-ring-offset-shadow": "0 0 #0000",
			"--tw-ring-offset-width": "0px",
			"--tw-ring-shadow": "0 0 #0000",
			"--tw-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-scroll-snap-strictness": "proximity",
			"--tw-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-slashed-zero": "var(--tw-empty,/**/ /**/)",
			"--tw-transfrom-translate-default": "translate(var(--tw-translate-x, 0), var(--tw-translate-y, 0))",
		},
		"::backdrop": {
			"--tw-backdrop-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-opacity": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-backdrop-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-blur": "var(--tw-empty,/**/ /**/)",
			"--tw-border-spacing-x": "0",
			"--tw-border-spacing-y": "0",
			"--tw-brightness": "var(--tw-empty,/**/ /**/)",
			"--tw-contrast": "var(--tw-empty,/**/ /**/)",
			"--tw-drop-shadow": "var(--tw-empty,/**/ /**/)",
			"--tw-grayscale": "var(--tw-empty,/**/ /**/)",
			"--tw-hue-rotate": "var(--tw-empty,/**/ /**/)",
			"--tw-invert": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-figure": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-fraction": "var(--tw-empty,/**/ /**/)",
			"--tw-numeric-spacing": "var(--tw-empty,/**/ /**/)",
			"--tw-ordinal": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-x": "var(--tw-empty,/**/ /**/)",
			"--tw-pan-y": "var(--tw-empty,/**/ /**/)",
			"--tw-pinch-zoom": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-color": "rgb(59 130 246 / 0.5)",
			"--tw-ring-inset": "var(--tw-empty,/**/ /**/)",
			"--tw-ring-offset-color": "#fff",
			"--tw-ring-offset-shadow": "0 0 #0000",
			"--tw-ring-offset-width": "0px",
			"--tw-ring-shadow": "0 0 #0000",
			"--tw-saturate": "var(--tw-empty,/**/ /**/)",
			"--tw-scroll-snap-strictness": "proximity",
			"--tw-sepia": "var(--tw-empty,/**/ /**/)",
			"--tw-slashed-zero": "var(--tw-empty,/**/ /**/)",
			"--tw-transfrom-translate-default": "translate(var(--tw-translate-x, 0), var(--tw-translate-y, 0))",
		},
	})
})
