export interface CorePluginFeatures {
	preflight: boolean
	accentColor: boolean
	accessibility: boolean
	alignContent: boolean
	alignItems: boolean
	alignSelf: boolean
	animation: boolean
	appearance: boolean
	aspectRatio: boolean
	backdropBlur: boolean
	backdropBrightness: boolean
	backdropContrast: boolean
	backdropFilter: boolean
	backdropGrayscale: boolean
	backdropHueRotate: boolean
	backdropInvert: boolean
	backdropOpacity: boolean
	backdropSaturate: boolean
	backdropSepia: boolean
	backgroundAttachment: boolean
	backgroundBlendMode: boolean
	backgroundClip: boolean
	backgroundColor: boolean
	backgroundImage: boolean
	backgroundOrigin: boolean
	backgroundPosition: boolean
	backgroundRepeat: boolean
	backgroundSize: boolean
	blur: boolean
	borderCollapse: boolean
	borderColor: boolean
	borderRadius: boolean
	borderStyle: boolean
	borderSpacing: boolean
	borderWidth: boolean
	boxDecorationBreak: boolean
	boxShadow: boolean
	boxShadowColor: boolean
	boxSizing: boolean
	breakAfter: boolean
	breakBefore: boolean
	breakInside: boolean
	brightness: boolean
	caretColor: boolean
	clear: boolean
	columns: boolean
	container: boolean
	content: boolean
	contrast: boolean
	cursor: boolean
	display: boolean
	divideColor: boolean
	divideStyle: boolean
	divideWidth: boolean
	dropShadow: boolean
	fill: boolean
	filter: boolean
	flex: boolean
	flexBasis: boolean
	flexDirection: boolean
	flexGrow: boolean
	flexShrink: boolean
	flexWrap: boolean
	float: boolean
	fontFamily: boolean
	fontSize: boolean
	fontSmoothing: boolean
	fontStyle: boolean
	fontVariantNumeric: boolean
	fontWeight: boolean
	gap: boolean
	gradientColorStops: boolean
	grayscale: boolean
	gridAutoColumns: boolean
	gridAutoFlow: boolean
	gridAutoRows: boolean
	gridColumn: boolean
	gridColumnEnd: boolean
	gridColumnStart: boolean
	gridRow: boolean
	gridRowEnd: boolean
	gridRowStart: boolean
	gridTemplateColumns: boolean
	gridTemplateRows: boolean
	height: boolean
	hueRotate: boolean
	inset: boolean
	invert: boolean
	isolation: boolean
	justifyContent: boolean
	justifyItems: boolean
	justifySelf: boolean
	letterSpacing: boolean
	lineHeight: boolean
	listStylePosition: boolean
	listStyleType: boolean
	margin: boolean
	maxHeight: boolean
	maxWidth: boolean
	minHeight: boolean
	minWidth: boolean
	mixBlendMode: boolean
	objectFit: boolean
	objectPosition: boolean
	opacity: boolean
	order: boolean
	outlineColor: boolean
	outlineOffset: boolean
	outlineStyle: boolean
	outlineWidth: boolean
	overflow: boolean
	overscrollBehavior: boolean
	padding: boolean
	placeContent: boolean
	placeholderColor: boolean
	placeItems: boolean
	placeSelf: boolean
	pointerEvents: boolean
	position: boolean
	resize: boolean
	ringColor: boolean
	ringOffsetColor: boolean
	ringOffsetWidth: boolean
	ringWidth: boolean
	rotate: boolean
	saturate: boolean
	scale: boolean
	scrollBehavior: boolean
	scrollMargin: boolean
	scrollPadding: boolean
	scrollSnapAlign: boolean
	scrollSnapStop: boolean
	scrollSnapType: boolean
	sepia: boolean
	skew: boolean
	space: boolean
	stroke: boolean
	strokeWidth: boolean
	tableLayout: boolean
	textAlign: boolean
	textColor: boolean
	textDecoration: boolean
	textDecorationColor: boolean
	textDecorationStyle: boolean
	textDecorationThickness: boolean
	textIndent: boolean
	textOverflow: boolean
	textTransform: boolean
	textUnderlineOffset: boolean
	touchAction: boolean
	transform: boolean
	transformOrigin: boolean
	transitionDelay: boolean
	transitionDuration: boolean
	transitionProperty: boolean
	transitionTimingFunction: boolean
	translate: boolean
	userSelect: boolean
	verticalAlign: boolean
	visibility: boolean
	whitespace: boolean
	width: boolean
	willChange: boolean
	wordBreak: boolean
	zIndex: boolean
}
